version: "3.9"

services:
  telemedicine-service:
    build:
      context: ./services/telemedicine-service
    container_name: telemedicine-service
    ports:
      - "5007:5007"
    env_file:
      - ./services/telemedicine-service/.env.docker