const TELEMEDICINE_SERVICE_URL =
  import.meta.env.TELEMEDICINE_SERVICE_URL || "http://localhost:5007";

export const TELEMEDICINE_API_URL = `${TELEMEDICINE_SERVICE_URL}/api/telemedicine`;
export const TELEMEDICINE_UPLOADS_BASE_URL = TELEMEDICINE_SERVICE_URL;
