apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: smart-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: appointment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: APPOINTMENT_MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: INTERNAL_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INTERNAL_SERVICE_SECRET
            - name: DOCTOR_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DOCTOR_SERVICE_URL
            - name: PATIENT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PATIENT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NOTIFICATION_SERVICE_URL
            - name: TELEMEDICINE_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TELEMEDICINE_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PAYMENT_SERVICE_URL
