apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: smart-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest`n          imagePullPolicy: Never
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NOTIFICATION_MONGO_URI
            - name: INTERNAL_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INTERNAL_SERVICE_SECRET
