apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: smart-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PATIENT_MONGO_URI
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_SERVICE_URL
            - name: INTERNAL_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INTERNAL_SERVICE_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_API_SECRET