apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: smart-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
          env:
            - name: PORT
              value: "5006"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PAYMENT_MONGO_URI
            - name: INTERNAL_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INTERNAL_SERVICE_SECRET