apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  JWT_SECRET: "8vF!s9K@2mQxL7pZ1nR$4tW^6yU&3aB"
  INTERNAL_SERVICE_SECRET: "smart_healthcare_internal_secret_2026"
  JWT_EXPIRES_IN: "15d"

  AUTH_SERVICE_URL: "http://auth-service:5002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5001"
  DOCTOR_SERVICE_URL: "http://doctor-service:5003"
  PATIENT_SERVICE_URL: "http://patient-service:5005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5004"
  PAYMENT_SERVICE_URL: "http://payment-service:5006"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:5007"
  AI_SYMPTOM_SERVICE_URL: "http://ai-symptom-service:5010"

  AUTH_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/auth-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  APPOINTMENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/appointment-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  DOCTOR_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/doctor-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  PATIENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/patient-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  NOTIFICATION_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/notification-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  PAYMENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/payment-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  TELEMEDICINE_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/telemedicine-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  AI_SYMPTOM_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/ai-symptom-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"

  CLOUDINARY_CLOUD_NAME: "dftsa8f2i"
  CLOUDINARY_API_KEY: "556581479483149"
  CLOUDINARY_API_SECRET: "RQ1CL-1ItzexjJ6SHd3gB9_Wfrw"

  GEMINI_API_KEY: "your_new_gemini_api_key"
  GEMINI_MODEL: "gemini-2.5-flash"

  ADMIN_USERNAME: "admin"
  ADMIN_EMAIL: "se38sliit@gmail.com"
  ADMIN_PASSWORD: "Admin1234"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "se38sliit@gmail.com"
  SMTP_PASS: "lshu kbfi uxkv baxy"
  SMTP_FROM: "SMART HEALTHCARE"

  EMAIL_USER: "samrthealthcare35@gmail.com"
  EMAIL_PASS: "uunk nokn nfwo dthr"

  TWILIO_ACCOUNT_SID: "ACd2b7da74891480f500d7de7a5c7684a5"
  TWILIO_AUTH_TOKEN: "9cf67b9f042f67cd8bf906a15fcc012e"
  TWILIO_PHONE_NUMBER: "+12604002951"
  TWILIO_WHATSAPP_NUMBER: "+14155238886"

  PAYHERE_MERCHANT_ID: "1234726"
  PAYHERE_MERCHANT_SECRET: "MTYyMzc2NjY5NDM1NTMzNTgyOTgyOTU4MDc0Mjk4NDE5MDA3MzY2MA=="
  PAYHERE_APP_ID: "4OVycDlkV1M4JH5Ex7FPHR3D5"
  PAYHERE_APP_SECRET: "4KEdqiffNty4PYgMJ6hrDG8hfJuewP7nK8bIcd59LoxU"
  PAYHERE_SANDBOX: "true"
  NOTIFY_URL: "https://nettie-weathered-orthogonally.ngrok-free.dev/api/payments/notify"
  RETURN_URL: "http://smart-healthcare.local/payment/success"
  CANCEL_URL: "http://smart-healthcare.local/payment/cancel"
