apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  JWT_SECRET: "8vF!s9K@2mQxL7pZ1nR$4tW^6yU&3aB"
  INTERNAL_SERVICE_SECRET: "smart_healthcare_internal_secret_2026"

  AUTH_SERVICE_URL: "http://auth-service:5002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5001"
  DOCTOR_SERVICE_URL: "http://doctor-service:5003"
  PATIENT_SERVICE_URL: "http://patient-service:5005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5004"
  PAYMENT_SERVICE_URL: "http://payment-service:5006"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:5007"
  AI_SYMPTOM_SERVICE_URL: "http://ai-symptom-service:5010"

  AUTH_MONGO_URI: "mongodb+srv://se_group_38:se38%40sliit@cluster0.kbxspji.mongodb.net/auth-service?retryWrites=true&w=majority"
  APPOINTMENT_MONGO_URI: "mongodb+srv://se_group_38:se38%40sliit@cluster0.kbxspji.mongodb.net/appointment-service?retryWrites=true&w=majority"
  DOCTOR_MONGO_URI: "mongodb+srv://se_group_38:se38%40sliit@cluster0.kbxspji.mongodb.net/doctor-service?retryWrites=true&w=majority"
  PATIENT_MONGO_URI: "mongodb+srv://se_group_38:se38%40sliit@cluster0.kbxspji.mongodb.net/patient-service?retryWrites=true&w=majority"
  NOTIFICATION_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/notification-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  PAYMENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/payment-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  TELEMEDICINE_MONGO_URI: "mongodb+srv://se_group_38:se38%40sliit@cluster0.kbxspji.mongodb.net/telemedicine-service?retryWrites=true&w=majority"
  AI_SYMPTOM_MONGO_URI: "mongodb+srv://se_group_38:se38%40sliit@cluster0.kbxspji.mongodb.net/ai-symptom-service?retryWrites=true&w=majority"

  CLOUDINARY_CLOUD_NAME: "dftsa8f2i"
  CLOUDINARY_API_KEY: "556581479483149"
  CLOUDINARY_API_SECRET: "RQ1CL-1ItzexjJ6SHd3gB9_Wfrw"

  GEMINI_API_KEY: "AIzaSyCQ4YkY4GRidjTlG03t3RKZITeRugzR-zg"
  GEMINI_MODEL: "gemini-2.5-flash"

  ADMIN_USERNAME: "admin"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "your-admin-password"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASS: "your-app-password"
  SMTP_FROM: "Smart Healthcare <your-email@gmail.com>"