apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  JWT_SECRET: "8vF!s9K@2mQxL7pZ1nR$4tW^6yU&3aB"
  INTERNAL_SERVICE_SECRET: "smart_healthcare_internal_secret_2026"
  JWT_EXPIRES_IN: "15d"

  AUTH_SERVICE_URL: "http://auth-service:5002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5001"
  DOCTOR_SERVICE_URL: "http://doctor-service:5003"
  PATIENT_SERVICE_URL: "http://patient-service:5005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5004"
  PAYMENT_SERVICE_URL: "http://payment-service:5006"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:5007"
  AI_SYMPTOM_SERVICE_URL: "http://ai-symptom-service:5010"

  AUTH_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/auth-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  APPOINTMENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/appointment-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  DOCTOR_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/doctor-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  PATIENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/patient-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  NOTIFICATION_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/notification-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  PAYMENT_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/payment-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  TELEMEDICINE_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/telemedicine-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"
  AI_SYMPTOM_MONGO_URI: "mongodb://se_group_38:se38%40sliit@ac-8lvrbnl-shard-00-00.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-01.kbxspji.mongodb.net:27017,ac-8lvrbnl-shard-00-02.kbxspji.mongodb.net:27017/ai-symptom-service?ssl=true&replicaSet=atlas-i0ei0o-shard-0&authSource=admin&retryWrites=true&w=majority"

  CLOUDINARY_CLOUD_NAME: "dftsa8f2i"
  CLOUDINARY_API_KEY: "your_cloudinary_api_key"
  CLOUDINARY_API_SECRET: "your_cloudinary_api_secret"

  GEMINI_API_KEY: "your_new_gemini_api_key"
  GEMINI_MODEL: "gemini-2.5-flash"

  ADMIN_USERNAME: "admin"
  ADMIN_EMAIL: "se38sliit@gmail.com"
  ADMIN_PASSWORD: "Admin1234"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "se38sliit@gmail.com"
  SMTP_PASS: "lshu kbfi uxkv baxy"
  SMTP_FROM: "SMART HEALTHCARE"

  EMAIL_USER: "samrthealthcare35@gmail.com"
  EMAIL_PASS: "uunk nokn nfwo dthr"

  TWILIO_ACCOUNT_SID: "your_twilio_account_sid"
  TWILIO_AUTH_TOKEN: "your_twilio_auth_token"
  TWILIO_PHONE_NUMBER: "your_twilio_phone_number"
  TWILIO_WHATSAPP_NUMBER: "your_twilio_whatsapp_number"

  PAYHERE_MERCHANT_ID: "1234726"
  PAYHERE_MERCHANT_SECRET: "NDE0ODM2NjI3MjQxNDUyMzk0MDkxNDY4ODc2NDUwMjk0MTM0OTY2"
  PAYHERE_APP_ID: "4OVybzgaici4JH5Ex7FPHR3D5"
  PAYHERE_APP_SECRET: "8Qq9de9AcL78LOcuI3szLP8ggjJ4KjMxi4jmmlsHN1aX"
  PAYHERE_SANDBOX: "true"
  NOTIFY_URL: "https://your-ngrok-url/api/payments/notify"
  RETURN_URL: "http://localhost:5173/payment/success"
  CANCEL_URL: "http://localhost:5173/payment/cancel"
