apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: smart-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5007
          env:
            - name: PORT
              value: "5007"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TELEMEDICINE_MONGO_URI
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_SERVICE_URL
            - name: INTERNAL_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: INTERNAL_SERVICE_SECRET